// ========================================
// Shoal Area Export
// ========================================
// Shoal: Bluefin
// Shoal ID: 59738
// Generated: 2025-12-21 16:21:01
// Total waypoints: 227
// Stop points: 12
// Stop duration: Retrieved from Shoal.BLUEFIN.getStopDuration()
// ========================================

package com.duckblade.osrs.sailing.features.trawling.ShoalPathData;

import com.duckblade.osrs.sailing.features.trawling.Shoal;
import com.duckblade.osrs.sailing.features.trawling.ShoalAreaData;
import com.duckblade.osrs.sailing.features.trawling.ShoalWaypoint;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;

/**
 * Shoal area definition for Bluefin (ID: 59738)
 * Contains waypoint path and area bounds.
 * Stop duration is retrieved from the Shoal enum.
 * Generated by ShoalPathTracker on 2025-12-21 16:21:01
 */
public class BluefinBuccaneersHaven implements ShoalAreaData {

	/** Area bounds for this shoal region */
	public static final WorldArea AREA = new WorldArea(1962, 3590, 312, 202, 0);

	/** Shoal type for this area */
	public static final Shoal SHOAL_TYPE = Shoal.BLUEFIN;

	/** Complete waypoint path with stop point information */
	public static final ShoalWaypoint[] WAYPOINTS = {
		new ShoalWaypoint(new WorldPoint(2215, 3684, 0), true),
		new ShoalWaypoint(new WorldPoint(2215, 3673, 0), false),
		new ShoalWaypoint(new WorldPoint(2217, 3669, 0), false),
		new ShoalWaypoint(new WorldPoint(2218, 3668, 0), false),
		new ShoalWaypoint(new WorldPoint(2221, 3667, 0), false),
		new ShoalWaypoint(new WorldPoint(2225, 3665, 0), false),
		new ShoalWaypoint(new WorldPoint(2242, 3665, 0), false),
		new ShoalWaypoint(new WorldPoint(2243, 3664, 0), false),
		new ShoalWaypoint(new WorldPoint(2246, 3663, 0), false),
		new ShoalWaypoint(new WorldPoint(2248, 3662, 0), false),
		new ShoalWaypoint(new WorldPoint(2251, 3660, 0), false),
		new ShoalWaypoint(new WorldPoint(2255, 3658, 0), false),
		new ShoalWaypoint(new WorldPoint(2258, 3655, 0), false),
		new ShoalWaypoint(new WorldPoint(2259, 3652, 0), false),
		new ShoalWaypoint(new WorldPoint(2260, 3651, 0), false),
		new ShoalWaypoint(new WorldPoint(2260, 3635, 0), true),
		new ShoalWaypoint(new WorldPoint(2260, 3634, 0), false),
		new ShoalWaypoint(new WorldPoint(2257, 3628, 0), false),
		new ShoalWaypoint(new WorldPoint(2252, 3623, 0), false),
		new ShoalWaypoint(new WorldPoint(2250, 3622, 0), false),
		new ShoalWaypoint(new WorldPoint(2249, 3621, 0), false),
		new ShoalWaypoint(new WorldPoint(2218, 3621, 0), false),
		new ShoalWaypoint(new WorldPoint(2216, 3621, 0), false),
		new ShoalWaypoint(new WorldPoint(2214, 3622, 0), false),
		new ShoalWaypoint(new WorldPoint(2213, 3623, 0), false),
		new ShoalWaypoint(new WorldPoint(2211, 3624, 0), false),
		new ShoalWaypoint(new WorldPoint(2209, 3626, 0), false),
		new ShoalWaypoint(new WorldPoint(2209, 3627, 0), false),
		new ShoalWaypoint(new WorldPoint(2207, 3630, 0), false),
		new ShoalWaypoint(new WorldPoint(2207, 3642, 0), false),
		new ShoalWaypoint(new WorldPoint(2206, 3644, 0), false),
		new ShoalWaypoint(new WorldPoint(2203, 3647, 0), false),
		new ShoalWaypoint(new WorldPoint(2201, 3648, 0), false),
		new ShoalWaypoint(new WorldPoint(2198, 3649, 0), false),
		new ShoalWaypoint(new WorldPoint(2196, 3649, 0), true),
		new ShoalWaypoint(new WorldPoint(2190, 3649, 0), false),
		new ShoalWaypoint(new WorldPoint(2188, 3648, 0), false),
		new ShoalWaypoint(new WorldPoint(2187, 3647, 0), false),
		new ShoalWaypoint(new WorldPoint(2186, 3647, 0), false),
		new ShoalWaypoint(new WorldPoint(2185, 3646, 0), false),
		new ShoalWaypoint(new WorldPoint(2184, 3644, 0), false),
		new ShoalWaypoint(new WorldPoint(2183, 3643, 0), false),
		new ShoalWaypoint(new WorldPoint(2182, 3643, 0), false),
		new ShoalWaypoint(new WorldPoint(2181, 3641, 0), false),
		new ShoalWaypoint(new WorldPoint(2181, 3610, 0), false),
		new ShoalWaypoint(new WorldPoint(2181, 3609, 0), false),
		new ShoalWaypoint(new WorldPoint(2180, 3607, 0), false),
		new ShoalWaypoint(new WorldPoint(2179, 3606, 0), false),
		new ShoalWaypoint(new WorldPoint(2177, 3605, 0), false),
		new ShoalWaypoint(new WorldPoint(2174, 3604, 0), false),
		new ShoalWaypoint(new WorldPoint(2162, 3604, 0), true),
		new ShoalWaypoint(new WorldPoint(2141, 3604, 0), false),
		new ShoalWaypoint(new WorldPoint(2138, 3603, 0), false),
		new ShoalWaypoint(new WorldPoint(2134, 3601, 0), false),
		new ShoalWaypoint(new WorldPoint(2132, 3601, 0), false),
		new ShoalWaypoint(new WorldPoint(2131, 3600, 0), false),
		new ShoalWaypoint(new WorldPoint(2100, 3600, 0), false),
		new ShoalWaypoint(new WorldPoint(2092, 3600, 0), false),
		new ShoalWaypoint(new WorldPoint(2091, 3601, 0), false),
		new ShoalWaypoint(new WorldPoint(2089, 3602, 0), false),
		new ShoalWaypoint(new WorldPoint(2086, 3604, 0), false),
		new ShoalWaypoint(new WorldPoint(2084, 3605, 0), false),
		new ShoalWaypoint(new WorldPoint(2081, 3606, 0), false),
		new ShoalWaypoint(new WorldPoint(2078, 3608, 0), false),
		new ShoalWaypoint(new WorldPoint(2076, 3609, 0), false),
		new ShoalWaypoint(new WorldPoint(2075, 3609, 0), false),
		new ShoalWaypoint(new WorldPoint(2072, 3611, 0), false),
		new ShoalWaypoint(new WorldPoint(2071, 3613, 0), false),
		new ShoalWaypoint(new WorldPoint(2070, 3616, 0), false),
		new ShoalWaypoint(new WorldPoint(2068, 3620, 0), false),
		new ShoalWaypoint(new WorldPoint(2068, 3621, 0), true),
		new ShoalWaypoint(new WorldPoint(2067, 3621, 0), false),
		new ShoalWaypoint(new WorldPoint(2066, 3622, 0), false),
		new ShoalWaypoint(new WorldPoint(2064, 3623, 0), false),
		new ShoalWaypoint(new WorldPoint(2061, 3624, 0), false),
		new ShoalWaypoint(new WorldPoint(2050, 3624, 0), false),
		new ShoalWaypoint(new WorldPoint(2047, 3625, 0), false),
		new ShoalWaypoint(new WorldPoint(2045, 3626, 0), false),
		new ShoalWaypoint(new WorldPoint(2039, 3632, 0), false),
		new ShoalWaypoint(new WorldPoint(2035, 3634, 0), false),
		new ShoalWaypoint(new WorldPoint(2027, 3634, 0), true),
		new ShoalWaypoint(new WorldPoint(2011, 3634, 0), false),
		new ShoalWaypoint(new WorldPoint(2009, 3635, 0), false),
		new ShoalWaypoint(new WorldPoint(2001, 3643, 0), false),
		new ShoalWaypoint(new WorldPoint(1999, 3644, 0), false),
		new ShoalWaypoint(new WorldPoint(1999, 3645, 0), false),
		new ShoalWaypoint(new WorldPoint(1985, 3659, 0), false),
		new ShoalWaypoint(new WorldPoint(1975, 3664, 0), false),
		new ShoalWaypoint(new WorldPoint(1974, 3665, 0), false),
		new ShoalWaypoint(new WorldPoint(1972, 3668, 0), false),
		new ShoalWaypoint(new WorldPoint(1972, 3677, 0), false),
		new ShoalWaypoint(new WorldPoint(1974, 3683, 0), false),
		new ShoalWaypoint(new WorldPoint(1976, 3685, 0), false),
		new ShoalWaypoint(new WorldPoint(1976, 3686, 0), false),
		new ShoalWaypoint(new WorldPoint(1977, 3688, 0), false),
		new ShoalWaypoint(new WorldPoint(1978, 3691, 0), false),
		new ShoalWaypoint(new WorldPoint(1980, 3694, 0), false),
		new ShoalWaypoint(new WorldPoint(1983, 3700, 0), false),
		new ShoalWaypoint(new WorldPoint(1991, 3708, 0), false),
		new ShoalWaypoint(new WorldPoint(1993, 3709, 0), false),
		new ShoalWaypoint(new WorldPoint(1996, 3711, 0), false),
		new ShoalWaypoint(new WorldPoint(1999, 3712, 0), false),
		new ShoalWaypoint(new WorldPoint(2001, 3713, 0), false),
		new ShoalWaypoint(new WorldPoint(2028, 3713, 0), true),
		new ShoalWaypoint(new WorldPoint(2030, 3714, 0), false),
		new ShoalWaypoint(new WorldPoint(2031, 3716, 0), false),
		new ShoalWaypoint(new WorldPoint(2033, 3717, 0), false),
		new ShoalWaypoint(new WorldPoint(2035, 3719, 0), false),
		new ShoalWaypoint(new WorldPoint(2035, 3720, 0), false),
		new ShoalWaypoint(new WorldPoint(2036, 3721, 0), false),
		new ShoalWaypoint(new WorldPoint(2036, 3727, 0), false),
		new ShoalWaypoint(new WorldPoint(2035, 3728, 0), false),
		new ShoalWaypoint(new WorldPoint(2034, 3730, 0), false),
		new ShoalWaypoint(new WorldPoint(2019, 3745, 0), false),
		new ShoalWaypoint(new WorldPoint(2017, 3746, 0), false),
		new ShoalWaypoint(new WorldPoint(2014, 3748, 0), false),
		new ShoalWaypoint(new WorldPoint(2012, 3749, 0), false),
		new ShoalWaypoint(new WorldPoint(2011, 3749, 0), false),
		new ShoalWaypoint(new WorldPoint(2010, 3750, 0), false),
		new ShoalWaypoint(new WorldPoint(2009, 3750, 0), false),
		new ShoalWaypoint(new WorldPoint(2007, 3754, 0), false),
		new ShoalWaypoint(new WorldPoint(2007, 3759, 0), true),
		new ShoalWaypoint(new WorldPoint(2007, 3767, 0), false),
		new ShoalWaypoint(new WorldPoint(2008, 3769, 0), false),
		new ShoalWaypoint(new WorldPoint(2009, 3770, 0), false),
		new ShoalWaypoint(new WorldPoint(2010, 3772, 0), false),
		new ShoalWaypoint(new WorldPoint(2011, 3773, 0), false),
		new ShoalWaypoint(new WorldPoint(2012, 3775, 0), false),
		new ShoalWaypoint(new WorldPoint(2014, 3776, 0), false),
		new ShoalWaypoint(new WorldPoint(2015, 3777, 0), false),
		new ShoalWaypoint(new WorldPoint(2019, 3779, 0), false),
		new ShoalWaypoint(new WorldPoint(2022, 3780, 0), false),
		new ShoalWaypoint(new WorldPoint(2024, 3781, 0), false),
		new ShoalWaypoint(new WorldPoint(2025, 3782, 0), false),
		new ShoalWaypoint(new WorldPoint(2027, 3782, 0), false),
		new ShoalWaypoint(new WorldPoint(2030, 3781, 0), false),
		new ShoalWaypoint(new WorldPoint(2034, 3779, 0), false),
		new ShoalWaypoint(new WorldPoint(2035, 3778, 0), false),
		new ShoalWaypoint(new WorldPoint(2036, 3776, 0), false),
		new ShoalWaypoint(new WorldPoint(2038, 3775, 0), false),
		new ShoalWaypoint(new WorldPoint(2039, 3772, 0), false),
		new ShoalWaypoint(new WorldPoint(2041, 3770, 0), false),
		new ShoalWaypoint(new WorldPoint(2042, 3767, 0), false),
		new ShoalWaypoint(new WorldPoint(2042, 3766, 0), false),
		new ShoalWaypoint(new WorldPoint(2043, 3765, 0), false),
		new ShoalWaypoint(new WorldPoint(2046, 3759, 0), false),
		new ShoalWaypoint(new WorldPoint(2049, 3756, 0), false),
		new ShoalWaypoint(new WorldPoint(2050, 3754, 0), false),
		new ShoalWaypoint(new WorldPoint(2051, 3754, 0), false),
		new ShoalWaypoint(new WorldPoint(2052, 3753, 0), false),
		new ShoalWaypoint(new WorldPoint(2055, 3751, 0), false),
		new ShoalWaypoint(new WorldPoint(2057, 3750, 0), false),
		new ShoalWaypoint(new WorldPoint(2060, 3749, 0), false),
		new ShoalWaypoint(new WorldPoint(2062, 3748, 0), false),
		new ShoalWaypoint(new WorldPoint(2075, 3748, 0), true),
		new ShoalWaypoint(new WorldPoint(2075, 3747, 0), false),
		new ShoalWaypoint(new WorldPoint(2077, 3746, 0), false),
		new ShoalWaypoint(new WorldPoint(2092, 3746, 0), false),
		new ShoalWaypoint(new WorldPoint(2100, 3742, 0), false),
		new ShoalWaypoint(new WorldPoint(2105, 3737, 0), false),
		new ShoalWaypoint(new WorldPoint(2106, 3735, 0), false),
		new ShoalWaypoint(new WorldPoint(2106, 3733, 0), false),
		new ShoalWaypoint(new WorldPoint(2105, 3731, 0), false),
		new ShoalWaypoint(new WorldPoint(2097, 3723, 0), false),
		new ShoalWaypoint(new WorldPoint(2093, 3721, 0), false),
		new ShoalWaypoint(new WorldPoint(2092, 3720, 0), false),
		new ShoalWaypoint(new WorldPoint(2090, 3716, 0), false),
		new ShoalWaypoint(new WorldPoint(2090, 3714, 0), false),
		new ShoalWaypoint(new WorldPoint(2091, 3714, 0), false),
		new ShoalWaypoint(new WorldPoint(2092, 3713, 0), false),
		new ShoalWaypoint(new WorldPoint(2110, 3713, 0), false),
		new ShoalWaypoint(new WorldPoint(2112, 3712, 0), true),
		new ShoalWaypoint(new WorldPoint(2114, 3711, 0), false),
		new ShoalWaypoint(new WorldPoint(2144, 3711, 0), false),
		new ShoalWaypoint(new WorldPoint(2153, 3711, 0), false),
		new ShoalWaypoint(new WorldPoint(2156, 3712, 0), false),
		new ShoalWaypoint(new WorldPoint(2157, 3713, 0), false),
		new ShoalWaypoint(new WorldPoint(2163, 3716, 0), false),
		new ShoalWaypoint(new WorldPoint(2166, 3718, 0), false),
		new ShoalWaypoint(new WorldPoint(2168, 3718, 0), false),
		new ShoalWaypoint(new WorldPoint(2169, 3719, 0), false),
		new ShoalWaypoint(new WorldPoint(2170, 3721, 0), false),
		new ShoalWaypoint(new WorldPoint(2172, 3722, 0), false),
		new ShoalWaypoint(new WorldPoint(2175, 3728, 0), false),
		new ShoalWaypoint(new WorldPoint(2175, 3738, 0), true),
		new ShoalWaypoint(new WorldPoint(2175, 3746, 0), false),
		new ShoalWaypoint(new WorldPoint(2176, 3749, 0), false),
		new ShoalWaypoint(new WorldPoint(2177, 3751, 0), false),
		new ShoalWaypoint(new WorldPoint(2177, 3753, 0), false),
		new ShoalWaypoint(new WorldPoint(2178, 3754, 0), false),
		new ShoalWaypoint(new WorldPoint(2179, 3756, 0), false),
		new ShoalWaypoint(new WorldPoint(2181, 3758, 0), false),
		new ShoalWaypoint(new WorldPoint(2182, 3760, 0), false),
		new ShoalWaypoint(new WorldPoint(2186, 3762, 0), false),
		new ShoalWaypoint(new WorldPoint(2187, 3763, 0), false),
		new ShoalWaypoint(new WorldPoint(2201, 3763, 0), false),
		new ShoalWaypoint(new WorldPoint(2204, 3761, 0), false),
		new ShoalWaypoint(new WorldPoint(2208, 3759, 0), false),
		new ShoalWaypoint(new WorldPoint(2213, 3759, 0), false),
		new ShoalWaypoint(new WorldPoint(2216, 3758, 0), false),
		new ShoalWaypoint(new WorldPoint(2226, 3753, 0), false),
		new ShoalWaypoint(new WorldPoint(2227, 3753, 0), false),
		new ShoalWaypoint(new WorldPoint(2229, 3752, 0), false),
		new ShoalWaypoint(new WorldPoint(2236, 3745, 0), false),
		new ShoalWaypoint(new WorldPoint(2237, 3745, 0), false),
		new ShoalWaypoint(new WorldPoint(2239, 3743, 0), false),
		new ShoalWaypoint(new WorldPoint(2240, 3741, 0), false),
		new ShoalWaypoint(new WorldPoint(2242, 3740, 0), false),
		new ShoalWaypoint(new WorldPoint(2243, 3738, 0), false),
		new ShoalWaypoint(new WorldPoint(2249, 3732, 0), false),
		new ShoalWaypoint(new WorldPoint(2250, 3730, 0), true),
		new ShoalWaypoint(new WorldPoint(2261, 3719, 0), false),
		new ShoalWaypoint(new WorldPoint(2262, 3719, 0), false),
		new ShoalWaypoint(new WorldPoint(2263, 3718, 0), false),
		new ShoalWaypoint(new WorldPoint(2264, 3716, 0), false),
		new ShoalWaypoint(new WorldPoint(2264, 3715, 0), false),
		new ShoalWaypoint(new WorldPoint(2263, 3713, 0), false),
		new ShoalWaypoint(new WorldPoint(2261, 3711, 0), false),
		new ShoalWaypoint(new WorldPoint(2260, 3711, 0), false),
		new ShoalWaypoint(new WorldPoint(2259, 3709, 0), false),
		new ShoalWaypoint(new WorldPoint(2249, 3704, 0), false),
		new ShoalWaypoint(new WorldPoint(2228, 3704, 0), false),
		new ShoalWaypoint(new WorldPoint(2222, 3701, 0), false),
		new ShoalWaypoint(new WorldPoint(2217, 3696, 0), false),
		new ShoalWaypoint(new WorldPoint(2216, 3694, 0), false),
		new ShoalWaypoint(new WorldPoint(2215, 3691, 0), false),
		new ShoalWaypoint(new WorldPoint(2215, 3684, 0), false),
	};

	// Singleton instance for interface access
	public static final BluefinBuccaneersHaven INSTANCE = new BluefinBuccaneersHaven();
	
	private BluefinBuccaneersHaven() {} // Private constructor
	
	// Interface implementations
	@Override
	public WorldArea getArea() { return AREA; }
	
	@Override
	public ShoalWaypoint[] getWaypoints() { return WAYPOINTS; }
	
	@Override
	public Shoal getShoalType() { return SHOAL_TYPE; }
}

// ========================================
// Integration with ShoalFishingArea enum
// ========================================
// Add this entry to ShoalFishingArea enum:
/*
BLUEFIN_AREA(ShoalBluefinArea.INSTANCE),
*/

// ========================================
// Usage Examples
// ========================================
// Check if player is in area:
// boolean inArea = ShoalBluefinArea.INSTANCE.contains(playerLocation);

// Get waypoints for rendering:
// WorldPoint[] path = ShoalBluefinArea.INSTANCE.getPositions();

// Get stop duration (from Shoal enum):
// int duration = ShoalBluefinArea.INSTANCE.getStopDuration();

// Access static fields directly:
// WorldArea area = ShoalBluefinArea.AREA;
// ShoalWaypoint[] waypoints = ShoalBluefinArea.WAYPOINTS;
// Shoal shoalType = ShoalBluefinArea.SHOAL_TYPE;

// ========================================
// Analysis Data
// ========================================
// Area bounds: 1962, 3590, 312, 202
// Stop points: 12 total
// Stop duration: Retrieved from BLUEFIN shoal type
// Stop point details:
// Stop 1 (index 0): WorldPoint(x=2215, y=3684, plane=0)
// Stop 2 (index 15): WorldPoint(x=2260, y=3635, plane=0)
// Stop 3 (index 34): WorldPoint(x=2196, y=3649, plane=0)
// Stop 4 (index 50): WorldPoint(x=2162, y=3604, plane=0)
// Stop 5 (index 70): WorldPoint(x=2068, y=3621, plane=0)
// Stop 6 (index 80): WorldPoint(x=2027, y=3634, plane=0)
// Stop 7 (index 103): WorldPoint(x=2028, y=3713, plane=0)
// Stop 8 (index 121): WorldPoint(x=2007, y=3759, plane=0)
// Stop 9 (index 154): WorldPoint(x=2075, y=3748, plane=0)
// Stop 10 (index 171): WorldPoint(x=2112, y=3712, plane=0)
// Stop 11 (index 184): WorldPoint(x=2175, y=3738, plane=0)
// Stop 12 (index 210): WorldPoint(x=2250, y=3730, plane=0)

// ========================================
// End of Export
// ========================================
