// ========================================
// Shoal Area Export
// ========================================
// Shoal: Vibrant
// Shoal ID: 59742
// Generated: 2025-12-21 15:32:53
// Total waypoints: 126
// Stop points: 8
// Area-based stop duration: -1 ticks
// ========================================

package com.duckblade.osrs.sailing.features.trawling.ShoalPathData;

import com.duckblade.osrs.sailing.features.trawling.Shoal;
import com.duckblade.osrs.sailing.features.trawling.ShoalAreaData;
import com.duckblade.osrs.sailing.features.trawling.ShoalWaypoint;
import net.runelite.api.coords.WorldArea;
import net.runelite.api.coords.WorldPoint;

/**
 * Shoal area definition for Vibrant (ID: 59742)
 * Contains waypoint path, area bounds, and stop duration.
 * Generated by ShoalPathTracker on 2025-12-21 15:32:53
 */
public class MarlinWeissmere implements ShoalAreaData {

	public static final WorldArea AREA = new WorldArea(2590, 3945, 278, 201, 0);
	public static final Shoal SHOAL_TYPE = Shoal.MARLIN;

	public static final ShoalWaypoint[] WAYPOINTS = {
		new ShoalWaypoint(new WorldPoint(2718, 3961, 0), true),
		new ShoalWaypoint(new WorldPoint(2718, 3960, 0), false),
		new ShoalWaypoint(new WorldPoint(2717, 3958, 0), false),
		new ShoalWaypoint(new WorldPoint(2715, 3956, 0), false),
		new ShoalWaypoint(new WorldPoint(2713, 3955, 0), false),
		new ShoalWaypoint(new WorldPoint(2680, 3955, 0), false),
		new ShoalWaypoint(new WorldPoint(2649, 3955, 0), false),
		new ShoalWaypoint(new WorldPoint(2642, 3955, 0), false),
		new ShoalWaypoint(new WorldPoint(2634, 3959, 0), false),
		new ShoalWaypoint(new WorldPoint(2631, 3960, 0), false),
		new ShoalWaypoint(new WorldPoint(2627, 3962, 0), false),
		new ShoalWaypoint(new WorldPoint(2624, 3964, 0), false),
		new ShoalWaypoint(new WorldPoint(2620, 3966, 0), false),
		new ShoalWaypoint(new WorldPoint(2614, 3968, 0), false),
		new ShoalWaypoint(new WorldPoint(2613, 3968, 0), true),
		new ShoalWaypoint(new WorldPoint(2612, 3968, 0), false),
		new ShoalWaypoint(new WorldPoint(2610, 3969, 0), false),
		new ShoalWaypoint(new WorldPoint(2609, 3971, 0), false),
		new ShoalWaypoint(new WorldPoint(2607, 3974, 0), false),
		new ShoalWaypoint(new WorldPoint(2605, 3978, 0), false),
		new ShoalWaypoint(new WorldPoint(2604, 3981, 0), false),
		new ShoalWaypoint(new WorldPoint(2601, 3985, 0), false),
		new ShoalWaypoint(new WorldPoint(2600, 3987, 0), false),
		new ShoalWaypoint(new WorldPoint(2600, 4019, 0), false),
		new ShoalWaypoint(new WorldPoint(2600, 4051, 0), false),
		new ShoalWaypoint(new WorldPoint(2600, 4069, 0), true),
		new ShoalWaypoint(new WorldPoint(2601, 4072, 0), false),
		new ShoalWaypoint(new WorldPoint(2602, 4074, 0), false),
		new ShoalWaypoint(new WorldPoint(2624, 4096, 0), false),
		new ShoalWaypoint(new WorldPoint(2641, 4113, 0), false),
		new ShoalWaypoint(new WorldPoint(2643, 4114, 0), false),
		new ShoalWaypoint(new WorldPoint(2646, 4116, 0), false),
		new ShoalWaypoint(new WorldPoint(2672, 4116, 0), false),
		new ShoalWaypoint(new WorldPoint(2674, 4115, 0), false),
		new ShoalWaypoint(new WorldPoint(2675, 4114, 0), false),
		new ShoalWaypoint(new WorldPoint(2677, 4111, 0), false),
		new ShoalWaypoint(new WorldPoint(2678, 4108, 0), false),
		new ShoalWaypoint(new WorldPoint(2682, 4100, 0), false),
		new ShoalWaypoint(new WorldPoint(2684, 4097, 0), false),
		new ShoalWaypoint(new WorldPoint(2685, 4094, 0), false),
		new ShoalWaypoint(new WorldPoint(2687, 4090, 0), false),
		new ShoalWaypoint(new WorldPoint(2689, 4088, 0), false),
		new ShoalWaypoint(new WorldPoint(2691, 4084, 0), false),
		new ShoalWaypoint(new WorldPoint(2692, 4081, 0), false),
		new ShoalWaypoint(new WorldPoint(2694, 4077, 0), false),
		new ShoalWaypoint(new WorldPoint(2696, 4074, 0), false),
		new ShoalWaypoint(new WorldPoint(2698, 4070, 0), false),
		new ShoalWaypoint(new WorldPoint(2699, 4067, 0), false),
		new ShoalWaypoint(new WorldPoint(2706, 4053, 0), false),
		new ShoalWaypoint(new WorldPoint(2708, 4050, 0), false),
		new ShoalWaypoint(new WorldPoint(2708, 4018, 0), false),
		new ShoalWaypoint(new WorldPoint(2708, 4010, 0), true),
		new ShoalWaypoint(new WorldPoint(2709, 4008, 0), false),
		new ShoalWaypoint(new WorldPoint(2718, 3999, 0), false),
		new ShoalWaypoint(new WorldPoint(2719, 3997, 0), false),
		new ShoalWaypoint(new WorldPoint(2721, 3996, 0), false),
		new ShoalWaypoint(new WorldPoint(2723, 3994, 0), false),
		new ShoalWaypoint(new WorldPoint(2724, 3992, 0), false),
		new ShoalWaypoint(new WorldPoint(2727, 3990, 0), false),
		new ShoalWaypoint(new WorldPoint(2730, 3989, 0), false),
		new ShoalWaypoint(new WorldPoint(2734, 3987, 0), false),
		new ShoalWaypoint(new WorldPoint(2737, 3985, 0), false),
		new ShoalWaypoint(new WorldPoint(2741, 3983, 0), false),
		new ShoalWaypoint(new WorldPoint(2744, 3982, 0), false),
		new ShoalWaypoint(new WorldPoint(2750, 3979, 0), false),
		new ShoalWaypoint(new WorldPoint(2754, 3978, 0), true),
		new ShoalWaypoint(new WorldPoint(2757, 3980, 0), false),
		new ShoalWaypoint(new WorldPoint(2760, 3981, 0), false),
		new ShoalWaypoint(new WorldPoint(2764, 3982, 0), false),
		new ShoalWaypoint(new WorldPoint(2770, 3986, 0), false),
		new ShoalWaypoint(new WorldPoint(2792, 4008, 0), false),
		new ShoalWaypoint(new WorldPoint(2793, 4009, 0), false),
		new ShoalWaypoint(new WorldPoint(2797, 4011, 0), false),
		new ShoalWaypoint(new WorldPoint(2812, 4011, 0), true),
		new ShoalWaypoint(new WorldPoint(2845, 4011, 0), false),
		new ShoalWaypoint(new WorldPoint(2853, 4011, 0), true),
		new ShoalWaypoint(new WorldPoint(2855, 4012, 0), false),
		new ShoalWaypoint(new WorldPoint(2856, 4014, 0), false),
		new ShoalWaypoint(new WorldPoint(2858, 4017, 0), false),
		new ShoalWaypoint(new WorldPoint(2858, 4020, 0), false),
		new ShoalWaypoint(new WorldPoint(2857, 4024, 0), false),
		new ShoalWaypoint(new WorldPoint(2853, 4028, 0), false),
		new ShoalWaypoint(new WorldPoint(2851, 4029, 0), false),
		new ShoalWaypoint(new WorldPoint(2849, 4031, 0), false),
		new ShoalWaypoint(new WorldPoint(2848, 4033, 0), false),
		new ShoalWaypoint(new WorldPoint(2839, 4042, 0), false),
		new ShoalWaypoint(new WorldPoint(2837, 4043, 0), false),
		new ShoalWaypoint(new WorldPoint(2835, 4045, 0), false),
		new ShoalWaypoint(new WorldPoint(2834, 4047, 0), false),
		new ShoalWaypoint(new WorldPoint(2832, 4049, 0), false),
		new ShoalWaypoint(new WorldPoint(2830, 4050, 0), false),
		new ShoalWaypoint(new WorldPoint(2829, 4052, 0), false),
		new ShoalWaypoint(new WorldPoint(2825, 4056, 0), false),
		new ShoalWaypoint(new WorldPoint(2823, 4057, 0), false),
		new ShoalWaypoint(new WorldPoint(2822, 4059, 0), false),
		new ShoalWaypoint(new WorldPoint(2811, 4070, 0), false),
		new ShoalWaypoint(new WorldPoint(2809, 4071, 0), false),
		new ShoalWaypoint(new WorldPoint(2808, 4073, 0), false),
		new ShoalWaypoint(new WorldPoint(2790, 4091, 0), false),
		new ShoalWaypoint(new WorldPoint(2788, 4092, 0), false),
		new ShoalWaypoint(new WorldPoint(2787, 4094, 0), false),
		new ShoalWaypoint(new WorldPoint(2783, 4098, 0), false),
		new ShoalWaypoint(new WorldPoint(2781, 4099, 0), false),
		new ShoalWaypoint(new WorldPoint(2780, 4101, 0), false),
		new ShoalWaypoint(new WorldPoint(2776, 4105, 0), false),
		new ShoalWaypoint(new WorldPoint(2774, 4106, 0), false),
		new ShoalWaypoint(new WorldPoint(2773, 4108, 0), false),
		new ShoalWaypoint(new WorldPoint(2757, 4124, 0), false),
		new ShoalWaypoint(new WorldPoint(2755, 4125, 0), false),
		new ShoalWaypoint(new WorldPoint(2754, 4127, 0), false),
		new ShoalWaypoint(new WorldPoint(2752, 4129, 0), false),
		new ShoalWaypoint(new WorldPoint(2750, 4130, 0), false),
		new ShoalWaypoint(new WorldPoint(2749, 4131, 0), false),
		new ShoalWaypoint(new WorldPoint(2748, 4133, 0), false),
		new ShoalWaypoint(new WorldPoint(2746, 4135, 0), true),
		new ShoalWaypoint(new WorldPoint(2744, 4136, 0), false),
		new ShoalWaypoint(new WorldPoint(2742, 4136, 0), false),
		new ShoalWaypoint(new WorldPoint(2739, 4134, 0), false),
		new ShoalWaypoint(new WorldPoint(2733, 4131, 0), false),
		new ShoalWaypoint(new WorldPoint(2720, 4118, 0), false),
		new ShoalWaypoint(new WorldPoint(2718, 4114, 0), false),
		new ShoalWaypoint(new WorldPoint(2718, 4083, 0), false),
		new ShoalWaypoint(new WorldPoint(2718, 4052, 0), false),
		new ShoalWaypoint(new WorldPoint(2718, 4020, 0), false),
		new ShoalWaypoint(new WorldPoint(2718, 3989, 0), false),
		new ShoalWaypoint(new WorldPoint(2718, 3962, 0), false),
	};

	public static final MarlinWeissmere INSTANCE = new MarlinWeissmere();
	
	private MarlinWeissmere() {} // Private constructor
	
	@Override
	public WorldArea getArea() { return AREA; }
	
	@Override
	public ShoalWaypoint[] getWaypoints() { return WAYPOINTS; }
	
	@Override
	public Shoal getShoalType() { return SHOAL_TYPE; }

}

// ========================================
// Integration with ShoalFishingArea enum
// ========================================
// Add this entry to ShoalFishingArea enum:
/*
VIBRANT_AREA(ShoalVibrantArea.INSTANCE),
*/

// ========================================
// Usage Examples
// ========================================
// Check if player is in area:
// boolean inArea = ShoalVibrantArea.INSTANCE.contains(playerLocation);

// Get waypoints for rendering:
// WorldPoint[] path = ShoalVibrantArea.INSTANCE.getPositions();

// Get stop duration:
// int duration = ShoalVibrantArea.INSTANCE.getStopDuration();

// Access static fields directly:
// WorldArea area = ShoalVibrantArea.AREA;
// ShoalWaypoint[] waypoints = ShoalVibrantArea.WAYPOINTS;

// ========================================
// Analysis Data
// ========================================
// Area bounds: 2590, 3945, 278, 201
// Stop points: 8 total
// Stop point details:
// Stop 1 (index 0): WorldPoint(x=2718, y=3961, plane=0)
// Stop 2 (index 14): WorldPoint(x=2613, y=3968, plane=0)
// Stop 3 (index 25): WorldPoint(x=2600, y=4069, plane=0)
// Stop 4 (index 51): WorldPoint(x=2708, y=4010, plane=0)
// Stop 5 (index 65): WorldPoint(x=2754, y=3978, plane=0)
// Stop 6 (index 73): WorldPoint(x=2812, y=4011, plane=0)
// Stop 7 (index 75): WorldPoint(x=2853, y=4011, plane=0)
// Stop 8 (index 114): WorldPoint(x=2746, y=4135, plane=0)

// ========================================
// End of Export
// ========================================
