package com.duckblade.osrs.sailing.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.ObjectID;

@RequiredArgsConstructor
@Getter
public enum CargoHoldTier
{

	WOOD(
		new int[]{
			ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_RAFT,
			ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_RAFT_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_2X5,
			ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_2X5_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_LARGE,
			ObjectID.SAILING_BOAT_CARGO_HOLD_REGULAR_LARGE_OPEN,
		}
	),
	OAK(
		new int[]{
			ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_RAFT,
			ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_RAFT_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_2X5,
			ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_2X5_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_LARGE,
			ObjectID.SAILING_BOAT_CARGO_HOLD_OAK_LARGE_OPEN,
		}
	),
	TEAK(
		new int[]{
			ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_RAFT,
			ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_RAFT_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_2X5,
			ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_2X5_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_LARGE,
			ObjectID.SAILING_BOAT_CARGO_HOLD_TEAK_LARGE_OPEN,
		}
	),
	MAHOGANY(
		new int[]{
			ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_RAFT,
			ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_RAFT_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_2X5,
			ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_2X5_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_LARGE,
			ObjectID.SAILING_BOAT_CARGO_HOLD_MAHOGANY_LARGE_OPEN,
		}
	),
	CAMPHOR(
		new int[]{
			ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_RAFT,
			ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_RAFT_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_2X5,
			ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_2X5_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_LARGE,
			ObjectID.SAILING_BOAT_CARGO_HOLD_CAMPHOR_LARGE_OPEN,
		}
	),
	IRONWOOD(
		new int[]{
			ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_RAFT,
			ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_RAFT_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_2X5,
			ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_2X5_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_LARGE,
			ObjectID.SAILING_BOAT_CARGO_HOLD_IRONWOOD_LARGE_OPEN,
		}
	),
	ROSEWOOD(
		new int[]{
			ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_RAFT,
			ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_RAFT_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_2X5,
			ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_2X5_OPEN,
			ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_LARGE,
			ObjectID.SAILING_BOAT_CARGO_HOLD_ROSEWOOD_LARGE_OPEN,
		}
	),
	;

	private final int[] gameObjectIds;

	public static CargoHoldTier fromGameObjectId(int id)
	{
		for (CargoHoldTier tier : values())
		{
			for (int objectId : tier.getGameObjectIds())
			{
				if (objectId == id)
				{
					return tier;
				}
			}
		}

		return null;
	}

}
