package com.duckblade.osrs.sailing.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.runelite.api.gameval.ObjectID;

@Slf4j
@RequiredArgsConstructor
@Getter
public enum Sail
{
	KANDARIN_1X3_LINEN(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_LINEN),
	KANDARIN_1X3_CANVAS(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_CANVAS),
	KANDARIN_1X3_COTTON(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_COTTON),
	KANDARIN_1X3_BLACK(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_BLACK),
	KANDARIN_1X3_YELLOW(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_YELLOW),
	KANDARIN_1X3_PURPLE(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_PURPLE),
	KANDARIN_1X3_GREEN(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_GREEN),
	KANDARIN_1X3_BLUE(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_BLUE),
	KANDARIN_1X3_PINK(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_PINK),
	KANDARIN_1X3_RED(ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_RED),
	KANDARIN_2X5_LINEN(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_LINEN),
	KANDARIN_2X5_CANVAS(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_CANVAS),
	KANDARIN_2X5_COTTON(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_COTTON),
	KANDARIN_2X5_BLACK(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_BLACK),
	KANDARIN_2X5_YELLOW(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_YELLOW),
	KANDARIN_2X5_PURPLE(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_PURPLE),
	KANDARIN_2X5_GREEN(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_GREEN),
	KANDARIN_2X5_BLUE(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_BLUE),
	KANDARIN_2X5_PINK(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_PINK),
	KANDARIN_2X5_RED(ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_RED),
	KANDARIN_3X8_LINEN(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_LINEN),
	KANDARIN_3X8_CANVAS(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_CANVAS),
	KANDARIN_3X8_COTTON(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_COTTON),
	KANDARIN_3X8_BLACK(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_BLACK),
	KANDARIN_3X8_YELLOW(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_YELLOW),
	KANDARIN_3X8_PURPLE(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_PURPLE),
	KANDARIN_3X8_GREEN(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_GREEN),
	KANDARIN_3X8_BLUE(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_BLUE),
	KANDARIN_3X8_PINK(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_PINK),
	KANDARIN_3X8_RED(ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_RED),
	;

	private final int gameObjectId;

	public static Sail fromGameObjectId(int id)
	{
		for (Sail sail : values())
		{
			if (sail.getGameObjectId() == id)
			{
				return sail;
			}
		}

		return null;
	}
}
